00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
print(torch.__version__)

2.8.0+cu126


In [ ]:
## Introduction to tensors

##

# scalar - has no dimensions, it's just a number.
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get an item out of a scalar and return it as a regular pyton integer.
scalar.item()

7

In [ ]:
# Vector - a vector usually has magnitude and direction
vector = torch.tensor([7, 7])

In [ ]:
# get the number of dimensions
vector.ndim

1

In [ ]:
# shape - two elements in the array
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],[3, 6, 9],[2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim
# Result: One three by three tensor.

3

In [ ]:
# to practice, write out your own tensor of
# any number of brackets and then interact with it.

In [ ]:
tensor2 = torch.tensor(
[[[1],[2],[3]],
[[4],[5],[6]]]
)
tensor2.size()

torch.Size([2, 3, 1])

### Random tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers.

https://docs.pytorch.org/docs/stable/generated/torch.rand.html


In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4157, 0.3503, 0.7950, 0.8049],
        [0.5259, 0.9667, 0.7874, 0.4719],
        [0.8855, 0.0953, 0.2356, 0.6503]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # x, y, RGB value
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# create a random tensor of whatever size and shape that you want.
random_waveform_tensor = torch.rand(size=(256, 1000)) # amplitude, time
random_waveform_tensor.shape, random_waveform_tensor.ndim

(torch.Size([256, 1000]), 2)

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# default data type
ones.dtype

torch.float32

In [ ]:
### Creating a range of tensors and tensors-like
# Use torch.arange()
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_onethousand = torch.arange(start=1, end=1001, step=150)
one_to_onethousand

tensor([  1, 151, 301, 451, 601, 751, 901])

In [ ]:
# Creating tensors with zeros_like(). Make a tensor in the same shape
# as the input but full of zeros.
ten_zeros = torch.zeros_like(input=one_to_onethousand)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes can be one of the 3 big problem areas people run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # data type
                               device=None, # whether this tensor will be on CPU or GPU
                               requires_grad=False) # if you want PyTorch to track gradients with this tensor's operations
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
# convert a float 32 tensor to float 16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor, float_16_tensor.dtype, float_32_tensor.dtype

(tensor([ 9., 36., 81.]), torch.float16, torch.float32)